authorz/urls.py
from django.urls import path
from . import views
from .views import UserLoginView, UserLogoutView

app_name = 'authorz'
urlpatterns = [
    path('user/login/', views.LoginAPIView.as_view(), name = 'login'),
    path('user/register/', views.RegistrationAPIView.as_view(), name = 'user_register'),
    path('user/search/', views.BasicSearchAPI.as_view(), name = 'Search'),
    path('user/follow/<int:pk>/', views.ProfileFollowAPIView.as_view(), name='profiles_messege'),
    path('user/profile/', views.ProfileListAPIView.as_view(), name='profiles_list'),
    path('user/profile/following/<int:pk>/', views.ProfileFollowingAPIView.as_view(), name='profiles_following'),
    path('user/profile/followers/<int:pk>/', views.ProfileFollowersAPIView.as_view(), name='profiles_followers'),
    path('user/profile/<int:pk>/', views.ProfileDetailAPIView.as_view(), name='profiles_detail'),
    path('user/profile/<int:pk>/update', views.ProfileUpdateAPIView.as_view(), name='profiles_update'),
    path('user/profile/<int:pk>/delete', views.ProfileDeleteAPIView.as_view(), name='profiles_delete'),
    path('login/', UserLoginView.as_view(), name='LogIn'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('users/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('reset/', views.ResetPass, name='reset'),
    path('reset/v/', views.ResetView.as_view(), name='resetV'),
    path('register', views.TestView, name= 'exp'),
    path('register/sc/', views.NewLogView.as_view(), name= 'exper'),
    path('posta/', views.PostListView.as_view(), name = 'fancy_post'),
    path('posta/create/', views.PostCreateView.as_view(), name = 'post_create'),
    path('posta/signed/', views.SignedListView.as_view(), name = 'signed_post'),
    path('users/follow/<slug:slug>/', views.ProfileFollow.as_view(), name='profile_messege'),
    path('search/', views.BasicSearch.as_view(), name = 'BaseSearch'),
    path('users/<str:slug>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('users/<str:slug>/following/', views.ProfileFollowingListView.as_view(), name='profile_following'),
    path('users/<str:slug>/followers/', views.ProfileFollowersListView.as_view(), name='profile_followers'),
    path('posta/<str:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('posta/<str:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posta/<str:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/', views.PostListAPIView.as_view(), name = 'simple_posts'),
    path('post/<int:pk>/', views.PostDetailAPIView.as_view(), name='posts_detail'),
    path('post/<int:pk>/update/', views.PostUpdateAPIView.as_view(), name='posts_update'),
    path('post/<int:pk>/delete/', views.PostDeleteAPIView.as_view(), name='posts_delete'),
    path('post/signed/', views.SignedListAPIView.as_view(), name = 'signed_posts'),
    path('chat/<slug:slug>/', views.Chat.as_view(), name='chat')
    
]

protected/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
    openapi.Info(
        title="API",
        default_version='v1',
        description="Welcome to the world of Jaseci",
        terms_of_service="https://www.jaseci.org",
        contact=openapi.Contact(email="jason@jaseci.org"),
        license=openapi.License(name="Awesome IP"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('authorz.urls', namespace='authorz')),
    re_path(r'^doc(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authorz/views.py
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db import transaction
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, View, UpdateView, CreateView, DeleteView
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from drf_yasg.views import get_schema_view
from rest_framework import status, generics, permissions
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.views import APIView

from . import serializers, forms
from .forms import LogForm, PassForm, ProfileUpdateForm, UserUpdateForm, UserLoginForm
from .models import Post, User, Profile, ChatMessage, ChatRoom
from .permissions import IsOwnerOrReadOnly
from .renderers import UserJSONRenderer
from .serializers import RegistrationSerializer, LoginSerializer, PostSerializer

class Chat(LoginRequiredMixin, View):
    model = Profile
    template_name = 'chat.html'
    def post(self, request, slug, *args, **kwargs):
        if not slug:
            return render(request, 'error.html', {'error': 'Slug is required.'}, status=400)
        try:
            receiver_profile = Profile.objects.get(slug=slug)
            reid = User.objects.filter(email=receiver_profile.user.email)
            receiver_user = reid.first()
        except Profile.DoesNotExist:
            return render(request, 'error.html', {'error': 'Profile not found.'}, status=404)
        sender_profile = request.user.profile
        
        def get_or_create_chat_room(user1, user2):
            existing_chat_room = ChatRoom.objects.filter(name=f'Chat between {user1.username} and {user2.username}') | ChatRoom.objects.filter(name=f'Chat between {user2.username} and {user1.username}')
            if existing_chat_room.exists():
                return existing_chat_room.first()
            else:
                new_chat_room = ChatRoom.objects.create(name=f'Chat between {user1.username} and {user2.username}')
                return new_chat_room
        chat_room = get_or_create_chat_room(request.user, receiver_user)
        messages = ChatMessage.objects.filter((Q(room=chat_room))).order_by('timestamp')
        print(chat_room)
        if request.method == 'POST':
            form = forms.ChatMessageForm(request.POST)
            if form.is_valid():
                new_message = form.save(commit=False)
                new_message.sender = request.user
                new_message.recipient = reid
                new_message.room_id = chat_room.id
                new_message.chat_room = chat_room
                new_message.con=form.cleaned_data['cch']
                new_message.save()
        else:
            form = forms.ChatMessageForm()
        return render(request, 'chat.html', {
            'chat_room': chat_room,
            'receiver_user': receiver_user,
            'sender_profile': sender_profile,
            'messages': messages,
            'form': form,
        })
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Chat'
        return context

class ProfileFollow(LoginRequiredMixin, View):
    model = Profile
    renderer_classes = (UserJSONRenderer,)
    @swagger_auto_schema(
        operation_summary="Follow or unfollow a user profile",
        manual_parameters=[
            openapi.Parameter(
                'slug',
                openapi.IN_PATH,
                description="User profile slug",
                type=openapi.TYPE_STRING,
                required=True,
            ),
        ],
        responses={302: "Redirect to profile detail page"},
    )
    def post(self, request, slug,  *args, **kwargs):
        if not slug:
            return Response({'error': 'Slug is required.'}, status=status.HTTP_400_BAD_REQUEST)
        try:
            profile = Profile.objects.get(slug=slug)
        except Profile.DoesNotExist:
            return Response({'error': 'Profile not found.'}, status=status.HTTP_404_NOT_FOUND)
        print(profile)
        print(request.user.profile.following.all())
        if profile in request.user.profile.following.all():
            request.user.profile.following.remove(profile)
        elif profile not in request.user.profile.following.all():
            request.user.profile.following.add(profile)
        return redirect('authorz:profile_detail', slug=slug)

class BasicSearch(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'index.html'
    def get(self, request, *args, **kwargs):
        form = forms.SearchForm()
        return render(request, 'index.html', {'form': form})
    def post(self, request, *args, **kwargs):
        form = forms.SearchForm(request.POST)
        print(request.POST)
        if form.is_valid():
            query = form.cleaned_data['que']
            poofs = User.objects.filter(Q(username__icontains = query) | Q(email__icontains = query))
            if poofs.exists():
                for user_object in poofs:
                    user_id = user_object.id
                    profile = Profile.objects.get(user=user_object)
                    print(f"Profile associated with user {user_id}: {profile}")
                    mata = profile.slug
                    return redirect(f'/api/users/{mata}/')
            else:
                return redirect(reverse('authorz:BaseSearch'))
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Search'
        return context        

class ProfileDetailView(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'authorz/profile_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Страница пользователя: {self.object.user.username}'
        return context

class ProfileFollowingListView(DetailView):
    template_name = 'authorz/profile_list.html'
    def post(self, request, slug):
        profile = get_object_or_404(Profile, slug=slug)
        followers = profile.following.all
        return render(request, self.template_name, {'profile': profile, 'followers': followers})

class ProfileFollowersListView(DetailView):
    template_name = 'authorz/profile_list.html'
    def post(self, request, slug):
        profile = get_object_or_404(Profile, slug=slug)
        followers = profile.followers.all
        return render(request, self.template_name, {'profile': profile, 'followers': followers})

class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'authorz/profile_edit.html'
    def get_object(self, queryset=None):
        return self.request.user.profile
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Редактирование профиля пользователя: {self.request.user.username}'
        if self.request.POST:
            context['user_form'] = UserUpdateForm(self.request.POST, instance=self.request.user)
        else:
            context['user_form'] = UserUpdateForm(instance=self.request.user)
        return context
    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context['user_form']
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                user_form.save()
                form.save()
            else:
                context.update({'user_form': user_form})
                return self.render_to_response(context)
        return super(ProfileUpdateView, self).form_valid(form)
    def get_success_url(self):
        return reverse_lazy('authorz:profile_detail', kwargs={'slug': self.object.slug})

def TestView(request):
    return render(request, 'authorz/user_register.html')
class NewLogView(APIView):
    permission_classes = (AllowAny,)
    renderer_classes = (UserJSONRenderer,)
    serializer_class = RegistrationSerializer
    @swagger_auto_schema(auto_schema=None)
    def get(self, request, *args, **kwargs):
        form = forms.RegForm()
        return render(request, 'authorz/user_register.html', {'form': form})
    @swagger_auto_schema(auto_schema=None)
    def post(self, request, *args, **kwargs):
        form = forms.RegForm(request.POST)
        print(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = {
                    "email": email,
                    "username": username,
                    "password": password
                }
            serializer = self.serializer_class(data=user)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            if self.password_check(email):
                return redirect(reverse('authorz:reset'))
            return redirect(reverse('authorz:fancy_post'))
    def password_check(self, email):
        try:
            user = User.objects.get(email=email)
            if user.last_password_update:
                time_difference = timezone.now() - user.last_password_update
                return time_difference > timedelta(days=20)
            return False
        except User.DoesNotExist:
            return False

def ResetPass(request):
    return render(request, 'authorz/reset.html')
class ResetView(APIView):
    permission_classes = (AllowAny,)
    renderer_classes = (UserJSONRenderer,)
    serializer_class = LoginSerializer

templates/authorz/feedback.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Контактная форма</h4>
            </div>
            <form method="post" action="{% reverse 'feedback' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Отправить письмо</button>
             </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/authorz/login.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="post" action="login/">
        {% csrf_token %}
        <p>Email:<br> <input name="email" type="email" /></p>
        <p>Password:<br> <input name="password" type="password"/></p>

        <button type="submit" value="Send">Login</button>
    </form>
</div>

{% endblock %}

templates/authorz/post_create.html
{% extends 'index.html' %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Добавление статьи</h4>
        </div>
        <form method="post" action="{% url 'authorz:post_create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Добавить статью</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/authorz/post_delete.html
{% extends 'index.html' %}


{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Удаление статьи</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                <i class="fas fa-info-circle"></i> Вы собираетесь удалить статью: <strong>{{ post.title }}</strong>, вы подтверждаете свое действие?
            </div>
            <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Удалить статью</button>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Отменить удаление</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/authorz/post_detail.html
{% extends 'index.html' %}



{% block content %}

        
        <strong>{{ Post.title }}</strong>

        <p>{{ Post.body }}</p>

        <p>{{ Post.owner }}</p>
        <small>{{ Post.created }}</small>

        <hr>
        {% if Post.thumbnail and Post.thumbnail.url %}
                <img src="{{ Post.thumbnail.url }}" alt="{{ Post.title }}" width="250"/>
        {% endif %}
        <hr>
        {% if request.user.is_authenticated and request.user == Post.owner %}
                <div type="row">
                        <a href="update/" class="btn btn-sm btn-primary" name="pupdate">Редактировать Пост</a>
                        <a href="delete/" class="btn btn-sm btn-danger btn-follow" name="pdelete">Удалить Пост</a>
                </div>
                
        {% endif %}

{% endblock %}

templates/authorz/post_list.html
{% extends 'post.html' %}


{% block content %}

    {% for Post in posts %}
        <div class="post-container">
            <strong>{{ Post.title }}</strong>

            {% if Post.thumbnail and Post.thumbnail.url %}
                <img src="{{ Post.thumbnail.url }}" alt="{{ Post.title }}" width="250"/>
            {% endif %}

            <p>{{ Post.body }}</p>
            <p>{{ Post.owner }}</p>
            <small>{{ Post.created }}</small>

            <a href="{{ Post.get_absolute_url }}" name="{{Post.slug}}">Подробнее</a>
            <hr>
        </div>
    {% endfor %}

{% endblock %}

templates/authorz/post_update.html
{% extends 'index.html' %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Обновление статьи: {{ Post.title }}</h4>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Обновить статью</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/authorz/profile_detail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="card border-0">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <figure>
                        <img src="{{ profile.avatar.url }}" class="img-fluid rounded-0" alt="{{ profile }}">
                    </figure>
                </div>
                <div class="col-md-9">
                     <h5 class="card-title">
                        {{ profile }}
                    </h5>
                    <div class="card-text">
                        <ul>
                            <li>Никнейм: {{ profile.user.username }}</li>
                            {% if profile.user.get_full_name %} <li>Имя и фамилия: {{ profile.user.get_full_name }}</li> {% endif %}
                            <li>Заходил: {{ profile.user.last_login }}</li>
                            <li>Дата рождения: {{ profile.birth_date }}</li>
                            <li>О себе: {{ profile.bio }}</li>
                        </ul>
                    {% if request.user.is_authenticated and request.user != profile.user %} {% if request.user.profile in profile.followers.all %}
                    <form method="post" action="{% url 'authorz:profile_messege' profile.slug %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-danger btn-follow">
                            Отписаться от {{ profile.user.username }}
                        </button>
                    </form>
                    <br>
                    <form method="post" action="{% url 'authorz:chat' profile.slug %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-primary">
                            Начать чат с {{ profile.user.username }}
                        </button>
                    </form>
					{% else %}
					<form method="post" action="{% url 'authorz:profile_messege' profile.slug %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-primary">
                            Подписаться на {{ profile.user.username }}
                        </button>
                    </form>
					{% endif %} {% elif request.user == profile.user %}
					<a href="{% url 'authorz:profile_edit' %}" class="btn btn-sm btn-primary" name="proedit">Редактировать профиль</a>
					{% endif %}
                    
                    </div>
                </div>
            </div>
        </div>
        <div class="card border-0">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <form method="post" action="{% url 'authorz:profile_following' profile.slug %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary me-2">
                                Подписки {{ profile.following.all|length }}
                            </button>
                        </form>
                        <div class="card-text">
                            <div class="row">
                                {% for following in profile.following.all %}
                                <div class="col-md-2">
                                    <a href="{{ following.get_absolute_url }}">
                                        <img src="{{ following.get_avatar }}" class="img-fluid rounded-1" alt="{{ following }}" />
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="post" action="{% url 'authorz:profile_followers' profile.slug %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary me-2">
                                Подписки {{ profile.followers.all|length }}
                            </button>
                        </form>
                        <div class="card-text">
                            <div class="row followers-box">
                                {% for follower in profile.followers.all %}
                                <div class="col-md-2" id="user-slug-{{ follower.slug }}">
                                    <a href="{{ follower.get_absolute_url }}">
                                        <img src="{{ follower.get_avatar }}" class="img-fluid rounded-1" alt="{{ follower }}" />    
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
{% endblock %}

templates/authorz/profile_edit.html
{% extends 'index.html' %}



{% block content %}

<div class="card mb-3 border-0 nth-shadow">

   <div class="card-body">

      <div class="card-title nth-card-title">

         <h4>Изменение профиля</h4>

      </div>

      <form method="post" enctype="multipart/form-data">

         {% csrf_token %}

         {{ user_form.as_p }}

         {{ form.as_p }}

         <div class="d-grid gap-2 d-md-block mt-2">

            <button type="submit" class="btn btn-dark">Подтвердить изменение профиля</button>

         </div>

      </form>

   </div>

</div>

{% endblock %}

templates/authorz/profile_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="row">
    <h2>Follows of {{ profile }}</h2>
    {% for follower in followers %}
    <div class="card border-0">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <figure>
                        <img src="{{ follower.avatar.url }}" class="img-fluid rounded-0" alt="{{ follower }}">
                    </figure>
                </div>
                <div class="col-md-9">
                     <h5 class="card-title">
                        {{ follower }}
                    </h5>
                    <div class="card-text">
                        <ul>
                            <li>Никнейм: {{ follower.user.username }}</li>
                            {% if follower.user.get_full_name %} <li>Имя и фамилия: {{ follower.user.get_full_name }}</li> {% endif %}
                            <li>Заходил: {{ follower.user.last_login }}</li>
                            <li>Дата рождения: {{ follower.birth_date }}</li>
                            <li>О себе: {{ follower.bio }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>  
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/authorz/profile_search.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="card border-0">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <figure>
                        <img src="{{ profile.avatar.url }}" class="img-fluid rounded-0" alt="{{ profile }}">
                    </figure>
                </div>
                <div class="col-md-9">
                     <h5 class="card-title">
                        {{ profile }}
                    </h5>
                    <div class="card-text">
                        <ul>
                            <li>Никнейм: {{ profile.user.username }}</li>
                            {% if profile.user.get_full_name %} <li>Имя и фамилия: {{ profile.user.get_full_name }}</li> {% endif %}
                            <li>Заходил: {{ profile.user.last_login }}</li>
                            <li>Дата рождения: {{ profile.birth_date }}</li>
                            <li>О себе: {{ profile.bio }}</li>
                        </ul>
                        {% if request.user.is_authenticated and request.user == profile.user %} 
					<a href="{% url 'authorz:profile_edit' %}" class="btn btn-sm btn-primary">Редактировать профиль</a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/authorz/reset.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Resetting Password</h1>
    <form method="post" action="v/">
        {% csrf_token %}
        <p>Email:<br> <input name="email" type="email" /></p>
        <p>Password:<br> <input name="password" type="password"/></p>
        <p>New Password:<br> <input name="npassword" type="password"/></p>
        <p>Repeat the new Password:<br> <input name="rpassword" type="password"/></p>
        <button type="submit" value="Send">Login</button>
    </form>
</div>
{% endblock %}

templates/authorz/user_login.html
{% extends 'index.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Авторизация на сайте</h4>
            </div>
            <form method="post" action="{% url 'authorz:LogIn' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Авторизоваться</button>
             </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/authorz/user_register.html
{% extends 'index.html' %}


{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Регистрация на сайте</h4>
        </div>
        <form method="post" action="{% url 'authorz:exper' %}" id="registrationForm" onsubmit="return validateForm()">
            {% csrf_token %}
            <p>Email:<br> <input name="email" type="email" /></p>
            <p>Username:<br> <input name="username" /></p>
            <p>Password:<br> <input name="password" id="password" type="password" /></p>
            <p>Confirm Password:<br> <input name="confirm_password" id="confirm_password" type="password" /></p>
            <p id="passwordMismatch" style="display: none; color: red;">Passwords do not match.</p>
            <p id="passwordLength" style="display: none; color: red;">Password must be at least 8 characters long.</p>
            <button type="submit" class="btn btn-dark mt-2">Зарегистрироваться</button>
        </form>
        <script>
            function validateForm() {
                const passwordInput = document.getElementById('password').value;
                const confirmPasswordInput = document.getElementById('confirm_password').value;
                
                // Check if passwords match
                if (passwordInput !== confirmPasswordInput) {
                    document.getElementById('passwordMismatch').style.display = 'block';
                    return false;  // Prevent form submission
                }
                
                // Check if password length is at least 8 characters
                if (passwordInput.length < 8) {
                    document.getElementById('passwordLength').style.display = 'block';
                    return false;  // Prevent form submission
                }
                
                // If all validations pass, allow form submission
                return true;
            }
        </script>
    </div>
</div>


{% endblock %}