authorz/urls.py
from django.urls import path
from . import views
from .views import UserLoginView, UserLogoutView

app_name = 'authorz'
urlpatterns = [
    path('user/login/', views.LoginAPIView.as_view(), name = 'login'),
    path('user/register/', views.RegistrationAPIView.as_view(), name = 'user_register'),
    path('user/search/', views.BasicSearchAPI.as_view(), name = 'Search'),
    path('user/follow/<int:pk>/', views.ProfileFollowAPIView.as_view(), name='profiles_messege'),
    path('user/profile/', views.ProfileListAPIView.as_view(), name='profiles_list'),
    path('user/profile/following/<int:pk>/', views.ProfileFollowingAPIView.as_view(), name='profiles_following'),
    path('user/profile/followers/<int:pk>/', views.ProfileFollowersAPIView.as_view(), name='profiles_followers'),
    path('user/profile/<int:pk>/', views.ProfileDetailAPIView.as_view(), name='profiles_detail'),
    path('user/profile/<int:pk>/update', views.ProfileUpdateAPIView.as_view(), name='profiles_update'),
    path('user/profile/<int:pk>/delete', views.ProfileDeleteAPIView.as_view(), name='profiles_delete'),
    path('login/', UserLoginView.as_view(), name='LogIn'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('users/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('reset/', views.ResetPass, name='reset'),
    path('reset/v/', views.ResetView.as_view(), name='resetV'),
    path('register', views.TestView, name= 'exp'),
    path('register/sc/', views.NewLogView.as_view(), name= 'exper'),
    path('posta/', views.PostListView.as_view(), name = 'fancy_post'),
    path('posta/create/', views.PostCreateView.as_view(), name = 'post_create'),
    path('posta/signed/', views.SignedListView.as_view(), name = 'signed_post'),
    path('users/follow/<slug:slug>/', views.ProfileFollow.as_view(), name='profile_messege'),
    path('search/', views.BasicSearch.as_view(), name = 'BaseSearch'),
    path('users/<str:slug>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('users/<str:slug>/following/', views.ProfileFollowingListView.as_view(), name='profile_following'),
    path('users/<str:slug>/followers/', views.ProfileFollowersListView.as_view(), name='profile_followers'),
    path('posta/<str:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('posta/<str:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posta/<str:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/', views.PostListAPIView.as_view(), name = 'simple_posts'),
    path('post/<int:pk>/', views.PostDetailAPIView.as_view(), name='posts_detail'),
    path('post/<int:pk>/update/', views.PostUpdateAPIView.as_view(), name='posts_update'),
    path('post/<int:pk>/delete/', views.PostDeleteAPIView.as_view(), name='posts_delete'),
    path('post/signed/', views.SignedListAPIView.as_view(), name = 'signed_posts'),
    path('chat/<slug:slug>/', views.Chat.as_view(), name='chat')
    
]

protected/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
    openapi.Info(
        title="API",
        default_version='v1',
        description="Welcome to the world of Jaseci",
        terms_of_service="https://www.jaseci.org",
        contact=openapi.Contact(email="jason@jaseci.org"),
        license=openapi.License(name="Awesome IP"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('authorz.urls', namespace='authorz')),
    re_path(r'^doc(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/chat.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>{{chat_room}}</h2>
            <div id="chat-messages">
                {% for message in messages %}
                <div><strong>{{ message.sender.username }}:</strong> {{ message.content }}</div>
                {% endfor %}
            </div>
            <form id="chat-form">
                <input type="text" id="message-input" placeholder="Type your message" name="cch">
                <button type="submit">Send Message</button>
            </form>
        </div>
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const chatForm = document.getElementById('chat-form');
    const messageInput = document.getElementById('message-input');
    const chatMessages = document.getElementById('chat-messages');

    const room_id = '{{ chat_room.id }}';  
    const chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + room_id + '/'
    );
    
    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const messageElement = document.createElement('div');
        messageElement.innerHTML = '<strong>' + data.sender + ':</strong> ' + data.message;
        chatMessages.appendChild(messageElement);
    };

    chatForm.addEventListener('submit', function(event) {
        console.log('Button clicked!');
        event.preventDefault();
        const message = messageInput.value;
        chatSocket.send(JSON.stringify({
            'content': message,
            'room_id': '{{ chat_room.id }}', 
            'recipient':'{{receiver_user.id}}',
        }));
        messageInput.value = '';
    });
    chatSocket.onerror = function(event) {console.error('WebSocket error:', event);};
});
</script>
{% endblock %}

templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Пример отправки сообщений</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
  <h1 class="text-center">Оставьте заявку</h1>
  <div class="container text-center">
    <div id="form_container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-actions form-group ">
          <button type="submit" class="form-control btn btn-success">Отправить</button>
        </div>
      </form>
    </div>
  </div>
</body>
</html>

templates/header.html
<header class="mt-3">
    <div class="px-3 py-2 text-bg-dark" style="border-radius: 10px 10px 0 0;">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/api/posta/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <img width="64" src="https://cdn-icons-png.flaticon.com/512/8277/8277654.png"/>
          </a>
          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="{% url 'authorz:fancy_post' %}" class="nav-link text-secondary">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"></use></svg>
                Главная
              </a>
            </li>
            <li>
              {% if request.user.is_authenticated %}
                <a href="{% url 'authorz:post_create' %}" class="nav-link text-white" name="add">
                  <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"></use></svg>
                  Добавить статью
                </a>
              {% else %}
                <a href="{% url 'authorz:LogIn' %}" class="nav-link text-white" name="add">
                  <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"></use></svg>
                  Добавить статью
                </a>
              {% endif %} 
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 bg-light mb-3" style="border-radius: 0 0 10px 10px;">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-3 mb-2 mb-lg-0 me-lg-auto"  method="post" action="{% url 'authorz:BaseSearch' %}"  >
          {% csrf_token %}
          <input class="form-control" placeholder="Поиск профиля по 'email' или логину" name='que' autocomplete="off">
        </form>
        {% if request.user.is_authenticated %}
          <a href="/api/posta/signed/" type="button" class="btn btn-secondary me-2">Новости</a>
          <a href="{% url 'authorz:profile_detail' request.user.profile.slug %}" type="button" class="btn btn-secondary me-2" name="{{request.user.username}}"> {{ request.user.username }}</a>
          <a href="{% url 'authorz:logout' %}" type="button" class="btn btn-primary">Выход</a>
        {% else %}
        <div class="text-end">
          <a href="{% url 'authorz:LogIn' %}" type="button" class="btn btn-light text-dark me-2">Авторизация</a>
          <a href="{% url 'authorz:exp' %}" type="button" class="btn btn-primary">Регистрация</a>
        </div>
        {% endif %}  
      </div>  
    </div>
  </header>

templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- INCLUDE CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        <div class="row">
            <div class="col-8">
            {% block content %}
            {% endblock %}
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/list.html
{% extends 'index.html' %}


{% block content %}

    {% for Post in posts %}
    <div class="card mb-3">
        <div class="row">
            <div class="col-4">
                {% if Post.thumbnail and Post.thumbnail.url %}
                <img src="{{ Post.thumbnail.url }}" class="card-img-top" alt="{{ Post.title }}">
            {% endif %}
                
            </div>
            <div class="col-8">
                <div class="card-body">
                    <h5 class="card-title">{{ Post.title }}</h5>
                    <div class="card-subtitle">{{ Post.owner }}</div>
                    <p class="card-text">{{ Post.sdescription }}</p>
                    <a href="{{ Post.get_absolute_url }}" name="{{Post.slug}}"">Подробнее</a>
                  </div>
                </div>
            </div>
      </div>
    {% endfor %}

{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center; /* Center-align text in the header */
 /* Add padding to the top and bottom of the header */
            background-color: #333; /* Example background color for the header */

        }
        main {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 85vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
        nav {
            background-color: rgb(110, 104, 101); /* Background color for the navigation bar */
        }

        .nav-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50px; /* Adjust the height of the navigation bar as needed */
        }

        .nav-item {
            margin: 0 15px; /* Adjust the spacing between navigation items */
        }

        .nav-item a {
            color: #fff; /* Text color for the navigation links */
            text-decoration: none; /* Remove underlines from links */
            font-weight: bold; /* Optionally set font weight */
        }
        header {
            height: 40px;
            align-items: center;
            justify-content: center;
            text-align: center; /* Center-align text in the header */
            padding: 0px 0; /* Add padding to the top and bottom of the header */
            background-color: #333; /* Example background color for the header */
            color: #fff; /* Example text color for the header */
        }
    </style>
    
</head>
    <body>
        <header>
            <h1>{% block header %}LogIn{% endblock %}</h1>
            <!-- Add any other header content here -->
        </header>
        <nav>
            <div class="nav-container">
                <div class="nav-item"><a href="/api/post/">Posts</a></div>
                <div class="nav-item"><a href="/api/ind/">Index</a></div>
                <div class="nav-item"><a href="/contact">Contact</a></div>
                <!-- Add more navigation items as needed -->
            </div>
        </nav>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- INCLUDE CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
    <style>
        header {
            text-align: center; /* Center-align text in the header */
            padding: 20px 0; /* Add padding to the top and bottom of the header */
            background-color: #333; /* Example background color for the header */
            color: #fff; /* Example text color for the header */
        }
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            align-items: top;
            justify-content: center;
            height: 100vh;
        }

        main {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            text-align: left;
        }

        .post-container {
            text-align: left; /* Center-align content within each post container */
            margin-bottom: 20px; /* Add space between each post */
            
        }

        img {
            display: block; /* Center the image within its container */
        }       
        nav {
            background-color: rgb(110, 104, 101); /* Background color for the navigation bar */
        }

        .nav-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50px; /* Adjust the height of the navigation bar as needed */
        }

        .nav-item {
            margin: 0 15px; /* Adjust the spacing between navigation items */
        }

        .nav-item a {
            color: #fff; /* Text color for the navigation links */
            text-decoration: none; /* Remove underlines from links */
            font-weight: bold; /* Optionally set font weight */
        }
    
    </style>
</head>
<body>

    <header>
        <h1>{% block header %}POSTS{% endblock %}</h1>
        <!-- Add any other header content here -->
    </header>

    <nav>
        <div class="nav-container">
            <div class="nav-item"><a href="/api/a/">LogIn</a></div>
            <div class="nav-item"><a href="/api/posta/">Index</a></div>
            <div class="nav-item"><a href="/contact">Contact</a></div>
            <!-- Add more navigation items as needed -->
        </div>
    </nav>
    <main>
        <div class="container">

            {% block content %}
    
    
    
            {% endblock %}
    
        </div>
    
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </main>
    <footer>
    </footer>

</body>
</html>